name: Build on Ubuntu 24.04

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3
      - name: Проверка хост-OC
        run: |
          cat /etc/os-release
          uname -a
